@startuml
 
left to right direction
:Người dùng: as user
:Hệ thống: as server
package "Quản lí phiên đăng nhập" {
    usecase "Đăng nhập" as login
    usecase "Đăng xuất" as logout
}
package "Xác thực người dùng" {
    usecase "Gửi mã xác thực" as otp
    usecase "Xác thực token" as verifyToken
}
package "Luồng tin nhắn" {
    usecase "Gửi tin nhắn đi" as incoming
    usecase "Nhận tin nhắn đến" as outgoing
}

package "Cơ sở dữ liệu" {
    usecase "Lưu tin nhắn tạm thời" as storing
    usecase "Lưu trữ dữ liệu người dùng, thiết bị và các khóa" as createUserData
    usecase "Lấy và xóa tin nhắn tạm thời" as getting
    usecase "Lấy dữ liệu người dùng, thiết bị và các khóa" as getUserData
}
package "Trò chuyện" {
    usecase "Xem tin nhắn" as view
    usecase "Tạo cuộc trò chuyện mới" as new
    usecase "Gửi tin nhắn" as sending
    usecase "Nhận tin nhắn" as receiving
}
usecase "Tìm kiếm số điện thoại" as searching
usecase "Nhận thông báo tin nhắn" as notification
user --> login
user --> logout
user --> sending
user --> receiving
user --> view
user --> new
new ..> searching: <<include>>
login ..> otp : <<include>>
login ..> verifyToken : <<include>>
server --> verifyToken
server --> incoming
server --> outgoing
server --> searching
note "Đăng nhập thành công" as logged
note "Khi người dùng ngoại tuyến (không kết nối)" as offline
note "Nếu có và khi người dùng trực tuyến (đã kết nối)" as online
note "Khi ứng dụng không được mở" as closingApp
note "Tìm kiếm có kết quả" as successfulSearching
verifyToken .. logged
logged ..> createUserData : <<extend>>
outgoing .. offline
offline ..> storing: <<extend>>
incoming .. online
online ..> getting: <<extend>>
receiving .. closingApp 
closingApp ..> notification: <<extend>>
searching .. successfulSearching
successfulSearching ..> getUserData: <<extend>>
@enduml